package main;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.OptionalDataException;
import java.io.StreamCorruptedException;
import java.math.BigInteger;
import java.security.*;
import java.util.Scanner;

public class DigitalSignature {
	String FILE_NAME ;
	String SIGNED_FILE_NAME;
	boolean DEBUG = false;
	
	public DigitalSignature(Scanner scanner){
		System.out.println("Enter File Name: (If reading file please do not enter \".signed\")");
		String FileName = scanner.next();
		this.FILE_NAME = FileName;
		this.SIGNED_FILE_NAME =  FILE_NAME + ".signed";
	}

	public void prepareFile(){
		
		File file;
		File output;
		FileInputStream fis;
		FileOutputStream fos;
		ObjectOutputStream OOS;
		
		try {
			// Setup: 
			// Create MD5 digeste, Retreives keys generated by KeyGen class
			MessageDigest digest = MessageDigest.getInstance("MD5");
			KeyGen key = new KeyGen();
			key.retrieveKeys();
			
			// Prepare File I/O
			file = new File(FILE_NAME);
			fis = new FileInputStream(file);

			output = new File(SIGNED_FILE_NAME);
			fos = new FileOutputStream(output);
			OOS = new ObjectOutputStream(fos);
			OOS.flush();

			
			//Read file, digest file contents using MD5, Create BigInteger 
			//using digest created
			byte[] b = new byte[(int)file.length()];
			fis.read(b);			
			byte[] digestedArray = digest.digest(b);
			BigInteger DigestedMessage = new BigInteger(digestedArray);
			
			//Create Signature using the digest created
			//digest^signature mod e
			BigInteger signed = DigestedMessage.modPow(key.getD(), key.getN());
			if(DEBUG){//-------------------------------------------DEBUG
				System.out.println("Signature: " + signed +
					         "\nMessage: " + new BigInteger(b) +
					         "\nDigestedMessage: " + DigestedMessage);
			}
			// Write signature and BigInteger representation of 
			// message to file.
			OOS.writeObject(signed);
			OOS.writeObject(new BigInteger(b));
			
			// Close open I/O 
			OOS.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e){
			e.printStackTrace();
		} catch (IOException e){
			e.printStackTrace();
		}
	}
	
	public void readFile(){
		try {
			// Create MD5 digeste, Retreives keys generated by KeyGen class
			MessageDigest digest = MessageDigest.getInstance("MD5");
			KeyGen kg = new KeyGen();
			kg.retrieveKeys();
			
			// Prepare Files I/O
			ObjectInputStream ois = new ObjectInputStream(new FileInputStream(new File(SIGNED_FILE_NAME)));
			
			// Read signature and BigInteger representation of message
			// from file
			BigInteger signed = (BigInteger) ois.readObject();
			BigInteger message = (BigInteger) ois.readObject();

			// Calculate M'
			BigInteger messageSigned = signed.modPow(kg.getE(), kg.getN());
			
			// Digest message using MD5 for comparison 
			byte[] digestedArray = digest.digest(message.toByteArray());
			BigInteger DigestedMessage = new BigInteger(digestedArray);
			
			if(DEBUG){//-------------------------------------------DEBUG
				System.out.println("Signature:      " + signed +
							 "\nMessage:        " + message + 
							 "\nMessage Signed: " + messageSigned +
							 "\nMessage Digest: " + DigestedMessage);
			}
			
			System.out.println("M' mod n = " + messageSigned.mod(kg.getN()));
			System.out.println("DM mod n = " + DigestedMessage.mod(kg.getN()));

			if(messageSigned.equals(DigestedMessage.mod(kg.getN()))){
				System.out.println("File has not been tampered with.\nMessage: " + new String(message.toByteArray()));
			} else {
				System.out.println("File has been tampered.");
			}
			// Close all open I/O 
			ois.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (StreamCorruptedException e){
			System.out.println("**-----------Error occurred. File may have been tampered with.-----------**");
		} catch(OptionalDataException e){
			System.out.println("**-----------Error occurred. File may have been tampered with.-----------**");
		} catch (IOException e){
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
